In [23]:
import sys
sys.path.append('..')
from scripts import models, utils, grid
from sklearn.model_selection import train_test_split
import pandas as pd

In [24]:
df = pd.read_csv('../datasets/titanic-limpio-numerico.csv')
df.sample()

,PassengerId,Survived,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Pclass_1,Pclass_2,Pclass_3,Embarked_C,Embarked_Q,Embarked_S
666,671.0,1.0,40.0,1.0,1.0,39.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [25]:
x, y = df.drop('Survived', axis = 1), df.Survived

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 123)
x_val_train, x_val_test, y_val_train, y_val_test = train_test_split(x_train, y_train, test_size = 0.30, random_state = 123)

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
rf_limits = {
    'MAX_n_estimators': 100,
    'MAX_max_depth': 20,
    'MAX_min_samples_split': 3,
    'MAX_min_samples_leaf': 2
}

rf_combinations = models.ClassifierModel.randomForestClassifier(**rf_limits).grid
print(len(rf_combinations))

5

In [28]:
grid, results = grid.GridSearch(RandomForestClassifier(), rf_combinations, x_val_train, y_val_train, cv = 2)

Fitting 2 folds for each of 576 candidates, totalling 1152 fits

c:\Documents\Proyectos\proyecto-titanic\env\lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
576 fits failed out of a total of 1152.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
576 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Documents\Proyectos\proyecto-titanic\env\lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Documents\Proyectos\proyecto-titanic\env\lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Documents\Proyectos\proyecto-titanic\env\lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Documents\Proyectos\proyecto-titanic\env\lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of RandomForestClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Documents\Proyectos\proyecto-titanic\env\lib\site-packages\sklearn\model_selection\_search.py:1103: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan 0.72580645 0.7281106  0.7281106  0.71658986
 0.73271889 0.72119816 0.7235023  0.72119816        nan        nan
        nan        nan        nan        nan        nan        nan
 0.73963134 0.71889401 0.73732719 0.74423963 0.73502304 0.7235023
 0.72580645 0.73041475        nan        nan        nan        nan
        nan        nan        nan        nan 0.76728111 0.75576037
 0.76267281 0.75115207 0.76036866 0.75806452 0.74654378 0.76497696
        nan        nan        nan        nan        nan        nan
        nan        nan 0.76728111 0.76497696 0.76958525 0.76728111
 0.76267281 0.75806452 0.76497696 0.75345622        nan        nan
        nan        nan        nan        nan        nan        nan
 0.77880184 0.76728111 0.76958525 0.76497696 0.76728111 0.7764977
 0.76728111 0.7764977         nan        nan        nan        nan
        nan        nan        nan        nan 0.7718894  0.78341014
 0.76958525 0.7764977  0.75345622 0.75806452 0.7718894  0.76267281
        nan        nan        nan        nan        nan        nan
        nan        nan 0.77880184 0.78341014 0.7718894  0.76958525
 0.7764977  0.77419355 0.7764977  0.76958525        nan        nan
        nan        nan        nan        nan        nan        nan
 0.7718894  0.75115207 0.77419355 0.79493088 0.7764977  0.7764977
 0.7718894  0.7718894         nan        nan        nan        nan
        nan        nan        nan        nan 0.74884793 0.7764977
 0.77880184 0.77880184 0.76267281 0.76497696 0.78341014 0.76728111
        nan        nan        nan        nan        nan        nan
        nan        nan 0.76267281 0.75345622 0.77419355 0.7718894
 0.7718894  0.78110599 0.76958525 0.76958525        nan        nan
        nan        nan        nan        nan        nan        nan
 0.75345622 0.76958525 0.7718894  0.7764977  0.7718894  0.78571429
 0.76958525 0.7718894         nan        nan        nan        nan
        nan        nan        nan        nan 0.7764977  0.76267281
 0.76497696 0.77419355 0.76728111 0.76267281 0.76728111 0.7764977
        nan        nan        nan        nan        nan        nan
        nan        nan 0.76728111 0.78341014 0.76728111 0.78110599
 0.78801843 0.7764977  0.76728111 0.76958525        nan        nan
        nan        nan        nan        nan        nan        nan
 0.75806452 0.77880184 0.7764977  0.76267281 0.7718894  0.77419355
 0.76728111 0.77880184        nan        nan        nan        nan
        nan        nan        nan        nan 0.76958525 0.7718894
 0.76036866 0.75576037 0.76958525 0.7718894  0.76728111 0.76267281
        nan        nan        nan        nan        nan        nan
        nan        nan 0.73732719 0.78110599 0.7718894  0.75345622
 0.78110599 0.76267281 0.76036866 0.77880184        nan        nan
        nan        nan        nan        nan        nan        nan
 0.75115207 0.75806452 0.77880184 0.75806452 0.77419355 0.76267281
 0.7764977  0.78341014        nan        nan        nan        nan
        nan        nan        nan        nan 0.74193548 0.78110599
 0.76036866 0.76958525 0.7718894  0.75576037 0.78571429 0.78571429
        nan        nan        nan        nan        nan        nan
        nan        nan 0.73502304 0.70967742 0.73732719 0.7281106
 0.72119816 0.7235023  0.7235023  0.72119816        nan        nan
        nan        nan        nan        nan        nan        nan
 0.74884793 0.73502304 0.74654378 0.74193548 0.74193548 0.73271889
 0.74884793 0.73963134        nan        nan        nan        nan
        nan        nan        nan        nan 0.75806452 0.76497696
 0.76497696 0.74193548 0.73963134 0.76036866 0.76267281 0.75345622
        nan        nan        nan        nan        nan        nan
        nan        nan 0.75115207 0.7718894  0.75345622 0.76958525
 0.76267281 0.75115207 0.77419355 0.76267281        nan        nan
        nan        nan        nan        nan        nan        nan
 0.75345622 0.76497696 0.76497696 0.75806452 0.75806452 0.76497696
 0.76497696 0.76267281        nan        nan        nan        nan
        nan        nan        nan        nan 0.76036866 0.76958525
 0.7764977  0.7718894  0.75576037 0.76036866 0.76267281 0.74884793
        nan        nan        nan        nan        nan        nan
        nan        nan 0.7764977  0.75345622 0.76267281 0.75576037
 0.7718894  0.76958525 0.7718894  0.76728111        nan        nan
        nan        nan        nan        nan        nan        nan
 0.7764977  0.76958525 0.7718894  0.77880184 0.76958525 0.76958525
 0.7764977  0.75806452        nan        nan        nan        nan
        nan        nan        nan        nan 0.7718894  0.76497696
 0.7718894  0.76728111 0.78110599 0.76958525 0.76958525 0.76728111
        nan        nan        nan        nan        nan        nan
        nan        nan 0.75806452 0.75345622 0.76036866 0.79032258
 0.76958525 0.78110599 0.75806452 0.77419355        nan        nan
        nan        nan        nan        nan        nan        nan
 0.76958525 0.75806452 0.76036866 0.76958525 0.77880184 0.76036866
 0.76497696 0.77880184        nan        nan        nan        nan
        nan        nan        nan        nan 0.76036866 0.76267281
 0.76267281 0.76728111 0.75576037 0.78341014 0.7718894  0.77880184
        nan        nan        nan        nan        nan        nan
        nan        nan 0.78801843 0.76497696 0.76728111 0.78801843
 0.7764977  0.76958525 0.76728111 0.75806452        nan        nan
        nan        nan        nan        nan        nan        nan
 0.79493088 0.76497696 0.75576037 0.76958525 0.76958525 0.76728111
 0.76267281 0.76267281        nan        nan        nan        nan
        nan        nan        nan        nan 0.7718894  0.7764977
 0.7718894  0.76267281 0.75806452 0.78110599 0.76728111 0.76497696
        nan        nan        nan        nan        nan        nan
        nan        nan 0.76958525 0.75576037 0.77419355 0.76958525
 0.76958525 0.76267281 0.7718894  0.76958525        nan        nan
        nan        nan        nan        nan        nan        nan
 0.78110599 0.76728111 0.7718894  0.76036866 0.76728111 0.77880184
 0.7718894  0.76958525        nan        nan        nan        nan
        nan        nan        nan        nan 0.75806452 0.76036866
 0.76036866 0.75806452 0.7718894  0.7718894  0.7764977  0.77419355]
  warnings.warn(

In [33]:
pd.DataFrame(results)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_min_samples_leaf,param_min_samples_split,param_n_estimators,params,split0_test_score,split1_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000000,0.000000,0.000000,0.000000,gini,2,1,1,20,"{'criterion': 'gini', 'max_depth': 2, 'min_sam...",NaN,NaN,NaN,NaN,289
1,0.003708,0.003708,0.000000,0.000000,gini,2,1,1,30,"{'criterion': 'gini', 'max_depth': 2, 'min_sam...",NaN,NaN,NaN,NaN,289
2,0.000000,0.000000,0.000000,0.000000,gini,2,1,1,40,"{'criterion': 'gini', 'max_depth': 2, 'min_sam...",NaN,NaN,NaN,NaN,289
3,0.000000,0.000000,0.000000,0.000000,gini,2,1,1,50,"{'criterion': 'gini', 'max_depth': 2, 'min_sam...",NaN,NaN,NaN,NaN,289
4,0.000710,0.000710,0.000000,0.000000,gini,2,1,1,60,"{'criterion': 'gini', 'max_depth': 2, 'min_sam...",NaN,NaN,NaN,NaN,289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,0.149277,0.000276,0.009499,0.000502,entropy,19,1,2,50,"{'criterion': 'entropy', 'max_depth': 19, 'min...",0.769585,0.746544,0.758065,0.011521,210
572,0.180742,0.007342,0.009001,0.000003,entropy,19,1,2,60,"{'criterion': 'entropy', 'max_depth': 19, 'min...",0.783410,0.760369,0.771889,0.011521,69
573,0.199112,0.006733,0.011506,0.001507,entropy,19,1,2,70,"{'criterion': 'entropy', 'max_depth': 19, 'min...",0.769585,0.774194,0.771889,0.002304,69
574,0.227867,0.009502,0.012500,0.000498,entropy,19,1,2,80,"{'criterion': 'entropy', 'max_depth': 19, 'min...",0.783410,0.769585,0.776498,0.006912,38
575,0.262758,0.012125,0.014499,0.001496,entropy,19,1,2,90,"{'criterion': 'entropy', 'max_depth': 19, 'min...",0.769585,0.778802,0.774194,0.004608,59