In [18]:
import pandas as pd
import json

import sys
sys.path.append('..')
from scripts import models

In [2]:
df = pd.read_csv('../datasets/results/randomForest-validation.csv')
df.head()

,model,hyperparameters,time,accuracy
0,RandomForestClassifier,"{'n_estimators': 290, 'criterion': 'gini', 'ma...",0:00:00,NaN
1,RandomForestClassifier,"{'n_estimators': 30, 'criterion': 'entropy', '...",0:00:00,NaN
2,RandomForestClassifier,"{'n_estimators': 150, 'criterion': 'entropy', ...",0:00:00,NaN
3,RandomForestClassifier,"{'n_estimators': 240, 'criterion': 'entropy', ...",0:00:00.000999,NaN
4,RandomForestClassifier,"{'n_estimators': 160, 'criterion': 'gini', 'ma...",0:00:00,NaN

In [20]:
rf_combinations = models.ClassifierModel.randomForestClassifier().combinations
print(len(rf_combinations))

4176

In [25]:
df.sort_values('accuracy', ascending = False)[:5]

,model,hyperparameters,time,accuracy
69,RandomForestClassifier,"{'n_estimators': 110, 'criterion': 'gini', 'ma...",0:00:02.466683,0.881720
462,RandomForestClassifier,"{'n_estimators': 130, 'criterion': 'entropy', ...",0:00:02.211184,0.881720
483,RandomForestClassifier,"{'n_estimators': 270, 'criterion': 'gini', 'ma...",0:00:06.184309,0.876344
453,RandomForestClassifier,"{'n_estimators': 210, 'criterion': 'entropy', ...",0:00:03.212416,0.876344
417,RandomForestClassifier,"{'n_estimators': 160, 'criterion': 'gini', 'ma...",0:00:02.547265,0.876344

In [39]:
hiper = pd.json_normalize(df.dropna(subset='accuracy').hyperparameters.apply(eval))
hiper.head()

,n_estimators,criterion,max_depth,min_samples_split,min_samples_leaf,accuracy
0,40,entropy,4,3,1,0.844086
1,100,entropy,9,2,1,0.865591
2,120,entropy,15,3,1,0.833333
3,50,entropy,2,2,1,0.811828
4,170,entropy,4,4,1,0.849462

In [41]:
hiper.sort_values(by = ['accuracy', 'n_estimators', 'max_depth'], ascending = [False, True, True])

,n_estimators,criterion,max_depth,min_samples_split,min_samples_leaf,accuracy
45,110,gini,7,2,1,0.881720
344,130,entropy,8,2,1,0.881720
189,70,entropy,8,4,1,0.876344
192,90,gini,6,3,1,0.876344
190,140,entropy,7,3,1,0.876344
...,...,...,...,...,...,...
143,20,gini,9,3,1,0.811828
3,50,entropy,2,2,1,0.811828
154,120,entropy,2,4,1,0.811828
225,110,gini,2,3,1,0.801075
179,130,gini,2,2,1,0.801075